apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webappv1
  labels:
    app: simple-webappv1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webappv1
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-webappv1
    spec:
      containers:
        - image: vijayramachandran/simple-webappv1
          imagePullPolicy: Always
          name: simple-webappv1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-webappv1
  labels:
    app: simple-webappv1
spec:
  type: LoadBalancer
  selector:
    app: simple-webappv1
  ports:
    - port: 7000
      targetPort: 80
      protocol: TCP