apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-simplewebapp
  labels:
    app: capstone-simplewebapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-simplewebapp
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-simplewebapp
    spec:
      containers:
        - image: vijayramachandran/simplewebapp
          imagePullPolicy: Always
          name: simplewebapp
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-simplewebapp
  labels:
    app: capstone-simplewebapp
spec:
  type: LoadBalancer
  selector:
    app: capstone-simplewebapp
  ports:
    - port: 7000
      targetPort: 80
      protocol: TCP