version: 2.1
orbs:
  aws-ecr-eks: signavio/aws-ecr-eks@2.4.0
  kubernetes: circleci/kubernetes@0.12.0
  
executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  linting:
    executor: python
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.webapp
            . ~/.webapp/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . ~/.webapp/bin/activate
            make lint
            
  buildingdocker-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            #Login to docker hub
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PWD
            # Build image and add a descriptive tag
            docker build --tag=simple-webapp .
            # Add the changes to the docker image
            docker-compose up -d
            # List docker images
            # Push image to a docker repository
            docker tag simple-webapp vijayramachandran/simple-webapp
            docker push vijayramachandran/simple-webapp
            
  cluster-deploy:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Simple-webapp
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: deployment.yml
          resource-name: deployment/simple-webapp
          
workflows:
  deployment:
    jobs:
      - linting
      - buildingdocker-image:
          requires:
            - linting
      - aws-eks/create-cluster:
          cluster-name: simple-webapp
          requires:
            - buildingdocker-image
      - cluster-deploy:
          cluster-name: simple-webapp
          requires: 
            - aws-eks/create-cluster